version: '3.8'

services:
  yew-ui:
    volumes:
      - type: bind
        source: ../
        target: /app 
    build:
      dockerfile: ../docker/Dockerfile.yew
    command: /bin/bash -c "cd app/ui && trunk serve --port ${TRUNK_SERVE_PORT:-8086} --address 0.0.0.0"
    environment:
      - CDN_URL=https://kouchan.b-cdn.net
      - API_PORT=${API_PORT:-8080}
      - API_HOST=${API_HOST:-localhost}
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-8086}
    ports:
      - "${TRUNK_SERVE_PORT:-8086}:${TRUNK_SERVE_PORT:-8086}"
  actix-api:
    volumes:
      - type: bind
        source: ../
        target: /app 
    build:
      dockerfile: ../docker/Dockerfile.actix
    secrets:
      - mongodb_key
      - cdn_access_key
    command: /bin/bash -c "cd app/api && cargo watch -x run"
    environment:
      - TMPDIR=/app/api/tmp
      - API_PORT=${API_PORT:-8080}
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-8086}
      - TRUNK_SERVE_HOST=${TRUNK_SERVE_HOST:-localhost}
      - AWS_ACCESS_KEY=AKIAZGK2J3QGWCLVJ4S5
      - MAX_BODY_LEN=${MAX_BODY_LEN:-2000}
      - MAX_TITLE_LEN=${MAX_TITLE_LEN:-100}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-3078000}
      - CDN_URL=https://storage.bunnycdn.com/kouchan
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"

secrets:
  mongodb_key:
    file: ../api/.mongodb_key
  cdn_access_key:
    file: ../api/.cdn_access_key
