version: '3.8'

services:
  yew-ui:
    volumes:
      - type: bind
        source: ../
        target: /app 
    build:
      dockerfile: ../docker/Dockerfile.yew
    command: /bin/bash -c "cd app/ui && trunk serve --port 8086 --address 0.0.0.0"
    environment:
      - API_PORT=${API_PORT:-8080}
      - TRUNK_SERVE_PORT=8086
    ports:
      - "8086:8086"
  actix-api:
    volumes:
      - type: bind
        source: ../
        target: /app 
    build:
      dockerfile: ../docker/Dockerfile.actix
    secrets:
      - mongodb_key
    command: /bin/bash -c "export TMPDIR=/app/api/tmp && cd app/api && cargo watch -x run"
    environment:
      - API_PORT=${API_PORT:-8080}
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-8086}
      - TRUNK_SERVE_HOST=localhost
      - MAX_BODY_LEN=2000
      - MAX_TITLE_LEN=100
      - MAX_FILE_SIZE=3078000
    ports:
      - "${API_PORT-8080}:${API_PORT:-8080}"

secrets:
  mongodb_key:
    file: ../.mongodb_key
